### ISSUE TITLE
Usage doc

### ISSUE THREAD

**Issue by SeeD-Seifer** [meuspedidos/intercom-android-xamarin#2]
Any document written in English on how to use this lib would be great.

**Comment by hudolfhess** [comment]
Hi, this package is a bind to https://github.com/intercom/intercom-android .
However, I recommend you to check the official package:
https://www.nuget.org/packages/Intercom.Dotnet.Client/

A long time ago in galaxy far, far away, when we create this bind, Intercom don't had a official package.

**Comment by SeeD-Seifer** [comment]
@hudolfhess thank you for the replay. Will check official dotnet package then.
